A2 priority queue
artyomzhibarev/PY111 pull request #3
Opened 2020-12-20 20:52 UTC by artyomzhibarev

Dequeue function not passed

2020-12-22 17:42 UTC, aeksei requested changes
1. Дальше будьте, пожалуйста, внимательнее при открытии pull request. У вас сюда попала очередь  
Один pull request - одна задача
2. Подскажите сложность добавления и удаления элемента из вашей очереди с приоритетом

2020-12-22 18:43 UTC, artyomzhibarev commented
> 1. Дальше будьте, пожалуйста, внимательнее при открытии pull request. У вас сюда попала очередь
>    Один pull request - одна задача
> 2. Подскажите сложность добавления и удаления элемента из вашей очереди с приоритетом

1. Я в целом не понял как так получилось и почему он подтянул другую задачу в эту ветку.
2. Enqueue, dequeue, peek - О(1)

2020-12-22 18:55 UTC, aeksei commented
> Enqueue, dequeue, peek - О(1)  

Нет((
Почитайте поподробнее про кучу, которую вы использовали для реализации очереди с приоритетом

2020-12-23 09:44 UTC, artyomzhibarev commented
> > Enqueue, dequeue, peek - О(1)
> 
> Нет((
> Почитайте поподробнее про кучу, которую вы использовали для реализации очереди с приоритетом

O(n log n)? - потому-что чтобы "поставить"/"убрать" элементы, нужно сдвинуть имеющиеся?

2020-12-24 15:42 UTC, aeksei commented
Тоже мимо))

2020-12-24 15:54 UTC, artyomzhibarev commented
> Тоже мимо))

O(logN) - добавление/удаление

2020-12-24 16:00 UTC, aeksei approved these changes

2020-12-24 16:07 UTC, merged